data_path: "C:/Users/PC/Desktop/TU/Master/MasterThesis/data/download_data/stratified_S2_points_wdate_filter_reduced_wgeotransform.csv"
pixel_size: 1.6
resample_size: 2.5
shape: [4, 512, 512]
outpath: "C:/Users/PC/Coding/GeoQuery/demo/test_publishing/"
download_method: 'sequential'
mask_label: [41]
create_gpkg: false
nodata_mode: "flag"
nodata_value: 0
verbose: True
