data_path: "/home/shollend/coding/download_stratified_ALL_S2_points_wdate_filter_combined.csv"
pixel_size: 1.6
resample_size: null # null
shape: [4, 1140, 1140]
outpath: "/data/USERS/shollend/orthophoto/austria_full_sequential"
download_method: 'sequential'
mask_label: [41]
create_gpkg: false
nodata_mode: "flag"
nodata_value: 0
verbose: True
