data_path: "C:/Users/PC/Coding/GeoQuery/demo/download_stratified_ALL_S2_points_wdate_filter_combined.csv"
pixel_size: 1.6
resample_size: null # null
shape: [4, 512, 512]
outpath: "C:/Users/PC/Coding/GeoQuery/demo/test_multiclass/"
download_method: 'sequential'
mask_label: [41]
create_gpkg: false
nodata_mode: "flag"
nodata_value: 0
verbose: True
all_classes: True
