data_path: "./samples/full_austria.csv"
pixel_size: 1.6
resample_size: 2.5
shape: [4, 512, 512]
outpath: "./output/demo_full_austria"
download_method: 'parallel'
mask_label:  [40, 41, 42, 48, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 72, 83, 84, 87, 88, 92, 95, 96]
create_gpkg: False
nodata_mode: "flag"
nodata_value: 0
verbose: False
